# Generated by Django 5.1 on 2024-10-09 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='investment_profile_id',
            new_name='investment_profile',
        ),
    ]
