# Generated by Django 5.1 on 2024-10-09 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=20)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.asset_types')),
            ],
        ),
        migrations.CreateModel(
            name='User_Investments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_time', models.DecimalField(decimal_places=10, default=1728503410.278303, max_digits=20)),
                ('is_buying', models.BooleanField()),
                ('amount', models.IntegerField()),
                ('assets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.assets')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
