# Generated by Django 5.1 on 2024-10-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_investments',
            name='date_time',
            field=models.CharField(default=1728359542.851358, max_length=18),
        ),
    ]
