# Generated by Django 5.1 on 2024-10-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_alter_user_investments_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_investments',
            name='date_time',
            field=models.IntegerField(default=1728413311.442847),
        ),
    ]
