# Generated by Django 5.1 on 2024-10-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_alter_user_investments_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_investments',
            old_name='assets_id',
            new_name='assets',
        ),
        migrations.RenameField(
            model_name='user_investments',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='user_investments',
            name='date_time',
            field=models.IntegerField(default=1728434303.190207),
        ),
    ]
